---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
source("Objects.R")
```

Row
-----------------------------------------------------------------------

### Median government expenditure on education, total (% of GDP)

```{r}
valueBox(icon = "fa-money-bill-alt", value = paste0(median_expenditure, " %"), color = "green")
```

### Median literacy rate, adult female (% of females ages 15 and above)

```{r}
valueBox(icon = "fa-book", value = paste0(literacy_f, " %"))
```

### Median literacy rate, adult male (% of males ages 15 and above)

```{r}
valueBox(icon = "fa-book", value = paste0(literacy_m, " %"), color ="teal")
```

### Median Trained teachers in secondary education (% of total teachers)

```{r}
valueBox(icon = "fa-chalkboard-teacher", value = paste0(train_teacher, " %"), color ="darkseagreen")
```

### Median Pupil-teacher ratio, primary

```{r}
valueBox(icon = "fa-school", value = paste0(pupl_tea_ratio), color ="darkslategray")
```

Row
-------------------------------------------------
### Adjusted net enrollment rate, primary (% of primary school age children)	

```{r}
#Place here ggplotly object of the timeseries 
ggplotly(timeseries_plot)
```


### Frequencies of compulsory education years in 2017 globally {data-width=200}

```{r}
#Place here compulsory_count object followed by the pipe and DT::datatable(rownames = FALSE) function
compulsory_counts %>% 
  DT::datatable()
```

